apiVersion: v1
data:
  ENV: dev
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"ENV":"dev"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"monitor-config","namespace":"linux-monitor"}}
  creationTimestamp: "2026-05-26T08:58:10Z"
  name: monitor-config
  namespace: linux-monitor
  resourceVersion: "6070"
  uid: 7ab09b42-40a6-43cc-bffa-7cd704c222c1
