apiVersion: apps/v1
kind: Deployment

metadata:
  name: linux-monitoring

spec:
  replicas: 1

  selector:
    matchLabels:
      app: linux-monitoring

  template:
    metadata:
      labels:
        app: linux-monitoring

    spec:
      imagePullSecrets:
        - name: ecr-secret

      containers:
        - name: linux-monitoring
          image: 042775549160.dkr.ecr.ap-south-1.amazonaws.com/linux-monitoring-system:latest
          imagePullPolicy: Always

