apiVersion: v1
kind: Service

metadata:
  name: linux-monitor-service
  namespace: linux-monitor

spec:

  selector:
    app: linux-monitor

  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

  type: NodePort
