services:

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped

    command:
      - "--collector.textfile.directory=/custom-metrics"

    volumes:
      - ../metrics:/custom-metrics

    ports:
      - "9100:9100"


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped

    ports:
      - "9090:9090"

    volumes:
      - ../observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

    depends_on:
      - node-exporter


  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped

    ports:
      - "3000:3000"

    volumes:
      - grafana-data:/var/lib/grafana


  linux-monitor:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    container_name: linux-monitor
    restart: unless-stopped

    volumes:
      - ../logs:/app/logs

    depends_on:
      - prometheus
      - node-exporter


volumes:
  prometheus-data:
  grafana-data:
