pipeline {
agent any

environment {
    AWS_REGION = "ap-south-1"
    AWS_ACCOUNT_ID = "042775549160"
    ECR_REPO = "linux-monitoring-system"
    INSTANCE_ID = "i-0f9d4e034e0e45f26"
}

stages {

    stage('Checkout') {
        steps {
            checkout scm
        }
    }

    stage('Verify Tools') {
        steps {
            sh '''
            docker --version
            aws --version
            '''
        }
    }

    stage('Build Docker Image') {
        steps {
            sh '''
            docker build -t linux-monitor-system -f docker/Dockerfile .
            '''
        }
    }

    stage('Login To ECR') {
        steps {
            sh '''
            aws ecr get-login-password --region $AWS_REGION | \
            docker login --username AWS --password-stdin \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
            '''
        }
    }

    stage('Push To ECR') {
        steps {
            sh '''
            docker tag linux-monitor-system:latest \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest

            docker push \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
            '''
        }
    }

    stage('Deploy To EC2') {
        steps {
            sh '''
            aws ssm send-command \
            --instance-ids $INSTANCE_ID \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy latest monitoring container" \
            --parameters '{
                "commands": [
                    "aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 042775549160.dkr.ecr.ap-south-1.amazonaws.com",
                    "docker pull 042775549160.dkr.ecr.ap-south-1.amazonaws.com/linux-monitoring-system:latest",
                    "docker stop linux-monitoring || true",
                    "docker rm linux-monitoring || true",
                    "docker run -d --name linux-monitoring --restart unless-stopped 042775549160.dkr.ecr.ap-south-1.amazonaws.com/linux-monitoring-system:latest"
                ]
            }'
            '''
        }
    }
}

post {
    success {
        echo 'Pipeline completed successfully!'
    }

    failure {
        echo 'Pipeline failed!'
    }
}

}

