pipeline {

 agent any

 stages {

  stage('Checkout') {
   steps {
    checkout scm
   }
  }

  stage('Smoke Test') {
   steps {
    sh 'make test'
   }
  }

  stage('Build') {
   steps {
    sh 'make build'
   }
  }

  stage('Deploy') {
   steps {
    sh 'make up'
   }
  }

 }

}
