#!/bin/bash

BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"

source "$BASE_DIR/config/thresholds.conf"
source "$BASE_DIR/utils/log-helper"
source "$BASE_DIR/utils/metrics-helper"

CPU_USAGE=$(top -bn1 | grep "Cpu(s)" | awk '{print 100 - $8}')
CPU_USAGE=${CPU_USAGE%.*}

if [ "$CPU_USAGE" -gt "$CPU_THRESHOLD" ]
then
    echo "CPU Usage High: $CPU_USAGE%"

    write_log "CPU ALERT - Usage: $CPU_USAGE%"

    update_metric "cpu_alerts_total" 1
else
    echo "CPU Healthy: $CPU_USAGE%"

    write_log "CPU HEALTHY - Usage: $CPU_USAGE%"
fi
