#!/bin/bash

BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"

source "$BASE_DIR/config/thresholds.conf"
source "$BASE_DIR/utils/log-helper"

MEMORY_USAGE=$(free | grep Mem | awk '{print ($3/$2) * 100.0}')
MEMORY_USAGE=${MEMORY_USAGE%.*}

if [ "$MEMORY_USAGE" -gt "$MEMORY_THRESHOLD" ]
then
    echo "Memory Usage High: $MEMORY_USAGE%"

    write_log "MEMORY ALERT - Usage: $MEMORY_USAGE%"
else
    echo "Memory Healthy: $MEMORY_USAGE%"

    write_log "MEMORY HEALTHY - Usage: $MEMORY_USAGE%"
fi
