#!/bin/bash

BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"

source "$BASE_DIR/utils/log-helper"

SERVICE_NAME=$1

STATUS=$(systemctl is-active "$SERVICE_NAME")

if [ "$STATUS" != "active" ]
then
    echo "$SERVICE_NAME is DOWN"

    write_log "SERVICE ALERT - $SERVICE_NAME DOWN"

    sudo systemctl restart "$SERVICE_NAME"

    write_log "AUTO-HEALING - Restarted $SERVICE_NAME"

    echo "$SERVICE_NAME restarted"
else
    echo "$SERVICE_NAME is RUNNING"

    write_log "SERVICE HEALTHY - $SERVICE_NAME RUNNING"
fi
