#!/bin/bash

SERVICES=("NetworkManager" "sshd" "cronie")

for service in "${SERVICES[@]}"
do
    if command -v systemctl >/dev/null 2>&1; then

        if systemctl is-active --quiet "$service"
        then
            echo "$service Healthy"

        else
            echo "$service DOWN"

            systemctl restart "$service" \
            || echo "Unable to restart $service"
        fi

    else
        echo "Skipping $service (container mode)"
    fi

done
